const nomePergunta = ("Nome completo:")
const nascimentoPergunta = ("Data de nascimento (utilize as /): ") 
const endereçoPergunta = ("Endereço:")
let CPFPergunta = ("CPF:")
let escolaridadePergunta = ("Escolaridade:")
let CNHPergunta = ("CNH:")
let filhosPergunta = ("Quantos filhos possui?:")
let cargoPergunta = ("Cargo atual:")
let salarioPergunta = ("Salário Atual:")
let comissaoPergunta = ("Recebe comissão? (Se sim, informe a porcentagem, caso não, responda com zero)")
let admissaoPergunta = ("Informe o ano de admissão")

const nomeResposta = prompt(nomePergunta)
const nascimentoResposta = prompt(nascimentoPergunta) 
const endereçoResposta = prompt(endereçoPergunta)
let CPFResposta = Number(prompt(CPFPergunta))
let escolaridadeResposta = prompt(escolaridadePergunta)
let CNHResposta = prompt(CNHPergunta)
let filhosResposta = prompt(filhosPergunta)
let cargoResposta = prompt(cargoPergunta)
let salarioResposta = prompt(salarioPergunta)
let comissaoResposta = prompt(comissaoPergunta)
let admissaoResposta = prompt(admissaoPergunta)

console.log(nomePergunta, nomeResposta)
console.log(nascimentoPergunta, nascimentoResposta)
console.log(endereçoPergunta, endereçoResposta)
console.log(CPFPergunta, CPFResposta)
console.log(escolaridadePergunta, escolaridadeResposta)
console.log(CNHPergunta, CNHResposta)
console.log(filhosPergunta, filhosResposta)
console.log(cargoPergunta, cargoResposta)
console.log(salarioPergunta, salarioResposta)
console.log(comissaoPergunta, comissaoResposta)
console.log(admissaoPergunta, admissaoResposta)

console.log(typeof nomeResposta)
console.log(typeof nascimentoResposta)
console.log(typeof endereçoResposta)
console.log(typeof CPFResposta)
console.log(typeof escolaridadeResposta)
console.log(typeof CNHResposta)
console.log(typeof filhosResposta)
console.log(typeof cargoResposta)
console.log(typeof salarioResposta)
console.log(typeof comissaoResposta)
console.log(typeof admissaoResposta)    