const nome = prompt("Nome completo:")
const nascimento = prompt("Data de nascimento (utilize as /): ") 
const endereço = prompt("Endereço:")
let CPF = Number(prompt("CPF:"))
let escolaridade = prompt("Escolaridade:")
let CNH = prompt("CNH:")
let filhos = prompt("Quantos filhos possui?:")
let cargo = prompt("Cargo atual:")
let salario = prompt("Salário Atual:")
let comissao = prompt("Recebe comissão? (Se sim, informe a porcentagem, caso não, responda com zero)")
let admissao = prompt("Informe o ano de admissão")

console.log(nome)
console.log(nascimento)
console.log(endereço)
console.log(CPF)
console.log(escolaridade)
console.log(CNH)
console.log(filhos)
console.log(cargo)
console.log(salario)
console.log(comissao)
console.log(admissao)

console.log(typeof nome)
console.log(typeof nascimento)
console.log(typeof endereço)
console.log(typeof CPF)
console.log(typeof escolaridade)
console.log(typeof CNH)
console.log(typeof filhos)
console.log(typeof cargo)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof admissao)    